### ISSUE TITLE
Is there a reason the main page (https://manual.ds-homebrew.com/) is so bland?

### ISSUE THREAD

**Issue by Void-Frost** [DS-Homebrew/twilight-manual#3]
Is this for compatibility with the DS? Or has it not just been styled yet? I will contribute some CSS styling to the best of my ability, but I don't want my efforts to be wasted.

Thanks.

**Comment by NightYoshi370** [comment]
It's supposed to be a basic list. If you want to fix it, feel free.

That page is not viewed on a true DS by the way. It's just something for people viewing the website.
In general, the website is meant for devs to test out their HTML writes, not necessarily for the public. If people want to view the manual, they should use the built in method.

**Comment by Void-Frost** [comment]
Great, thanks.
